'use strict';
let token='',view='overview';
const $=s=>document.querySelector(s);
const titles={external:'External response actions',overview:'Security overview',integrations:'Integration catalog',workflows:'Response workflows',rules:'Detection rules',events:'Event explorer',alerts:'Detections',cases:'Investigations',quarantine:'Data quality',audit:'Workspace activity'};
function el(tag,text,cls){const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;}
function notice(text){$('#notice').textContent=text;}
async function api(path,body){const r=await fetch(path,{method:body?'POST':'GET',headers:{Authorization:'Bearer '+token,...(body?{'Content-Type':'application/json'}:{})},...(body?{body:JSON.stringify(body)}:{})});const data=await r.json();if(!r.ok)throw Error(data.error||'Request failed');return data;}
function table(rows,columns,action){const wrap=el('div',undefined,'tablewrap');if(!rows.length){wrap.append(el('div','No records yet.','empty'));return wrap;}const t=el('table'),h=el('tr');columns.forEach(c=>h.append(el('th',c[0])));if(action)h.append(el('th','Action'));const head=el('thead');head.append(h);t.append(head);const body=el('tbody');for(const r of rows){const row=el('tr');columns.forEach(c=>{const value=typeof c[1]==='function'?c[1](r):r[c[1]];row.append(el('td',String(value??'')));});if(action){const td=el('td'),b=el('button',action.label);b.onclick=()=>run(()=>action.fn(r));td.append(b);row.append(td);}body.append(row);}t.append(body);wrap.append(t);return wrap;}
function date(seconds){return new Date(seconds*1000).toLocaleString();}
async function run(fn){try{await fn();}catch(e){notice(e.message);}}
async function load(){if(!token)return;$('#title').textContent=titles[view];const c=$('#content');c.replaceChildren();document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===view));
if(view==='overview'){const h=await api('/api/health'),stats=el('div',undefined,'stats');for(const [key,label,sub] of [['raw_events','Accepted events','Durable ingress receipts'],['normalized','Searchable events','Current analytics projection'],['alerts','Detections','Configurable native detections'],['quarantine','Needs attention','Preserved for diagnosis and replay']]){const card=el('article',undefined,'stat');card.append(el('div',label,'label'),el('div',h[key]===null?'Unavailable':h[key].toLocaleString(),'value'),el('small',sub));stats.append(card);}c.append(stats);const grid=el('div',undefined,'grid');for(const [title,text,ok] of [['Processing health',`${h.normalizer_pending} waiting for normalization · ${h.detector_pending} waiting for detection`,!h.worker_error&&!h.normalizer_pending&&!h.detector_pending],['Evidence handling','Retries preserve event identity. Quarantined records remain available. Local storage is not a production immutable archive.',!h.quarantine]]){const card=el('article',undefined,'card');card.append(el('span',ok?'Ready':'Review needed','pill'+(ok?'':' warning')),el('h2',title),el('p',text));grid.append(card);}c.append(grid);notice(h.worker_error?'One or more workers are unhealthy. Inspect process status.':h.analytics_available===false?'Analytics is unavailable; other processing may continue.':'Workspace updated · '+h.mode);}
if(view==='integrations'){const rows=await api('/api/integrations'),grid=el('div',undefined,'grid');rows.forEach(r=>{const card=el('article',undefined,'card');card.append(el('span',r.active?'Active':'Available','pill'),el('h2',r.name),el('p',r.description),el('p',`Version ${r.version} · ${r.fixture_count} fixture verified`));const b=el('button',r.active?'Revalidate activation':'Activate integration');b.onclick=()=>run(async()=>{await api('/api/integrations/activate',{package:r.id});notice('Integration activated.');await load();});card.append(b);if(r.active){const off=el('button','Deactivate');off.onclick=()=>run(async()=>{await api('/api/integrations/deactivate',{package:r.id});await load();});card.append(off);}grid.append(card);});c.append(grid);}
if(view==='rules'){
 const rows=await api('/api/rules');c.append(el('p','Rules declare fixed, sliding, or ordered-event windows. Simulation treats the selected rule as enabled, evaluates supplied samples, and does not write events or alerts.'));
 c.append(table(rows,[['Rule','title'],['Severity','severity'],['Mode',r=>r.window_mode||'fixed'],['Enabled',r=>r.enabled?'Yes':'No'],['Window',r=>r.window_seconds+' seconds'],['Threshold','threshold'],['Group',r=>r.group_by.join(', ')],['Trust','signature_status']],{label:'Simulate',fn:async r=>{
  const panel=el('article',undefined,'card');panel.append(el('h2',r.title));const toggle=el('button',r.enabled?'Disable for this tenant':'Enable for this tenant');toggle.onclick=()=>run(async()=>{await api('/api/rules/configure',{id:r.id,revision:r.revision,enabled:!r.enabled});await load();});panel.append(toggle);
  const text=el('textarea');text.setAttribute('aria-label','Normalized sample events JSON');text.rows=12;
  text.value=JSON.stringify([{source:'example',actor:'alice',ip:'192.0.2.1',outcome:'failure',message:'Synthetic authentication',event_time:Math.floor(Date.now()/1000)}],null,2);
  const button=el('button','Run simulation'),result=el('pre');button.onclick=()=>run(async()=>{const rule={...r,enabled:true};delete rule.revision;delete rule.signature_status;delete rule.configuration_source;delete rule.configuration_stale;result.textContent=JSON.stringify(await api('/api/rules/simulate',{rule,events:JSON.parse(text.value)}),null,2);});
  panel.append(text,button,result);c.append(panel);panel.scrollIntoView({behavior:'smooth'});
 }}));
}
if(view==='events'){
 const form=el('form'),row=el('div',undefined,'row'),fields={};
 for(const [name,label,type] of [['q','Message or actor','text'],['ip','Source IP','text'],['category','Category','text'],['action','Action','text'],['host','Host','text'],['target','Target','text'],['field','Nested field (process.file.path)','text'],['value','Field value (JSON scalar)','text'],['exists','Field exists (true/false; omit value)','text'],['after','From (local time)','datetime-local'],['before','Until (exclusive, local time)','datetime-local']]){const wrap=el('label',label),input=el('input');input.type=type;input.name=name;fields[name]=input;wrap.append(input);row.append(wrap);}
 const wrap=el('label','Outcome'),outcome=el('select');for(const value of ['','success','failure','unknown']){const option=el('option',value||'All');option.value=value;outcome.append(option);}fields.outcome=outcome;wrap.append(outcome);row.append(wrap,el('button','Search'));form.append(row);c.append(form);const results=el('div');c.append(results);
 async function search(){const params=new URLSearchParams();for(const [name,input] of Object.entries(fields)){if(input.value)params.set(name,['after','before'].includes(name)?new Date(input.value).toISOString():input.value);}const rows=await api('/api/search?'+params);results.replaceChildren(table(rows,[['Event time',r=>date(r.event_time)],['Category','category'],['Action','action'],['Target','target'],['Actor','actor'],['Source IP','ip'],['Outcome','outcome'],['Message','message']],{label:'Inspect',fn:async r=>{const detail=await api('/api/event?id='+encodeURIComponent(r.event_id));const panel=el('article',undefined,'card');panel.append(el('h2','Event evidence'),el('pre',JSON.stringify(detail,null,2)));results.append(panel);panel.scrollIntoView({behavior:'smooth'});}}));}
 form.onsubmit=e=>{e.preventDefault();run(search);};await search();
}
if(view==='alerts'){const rows=await api('/api/alerts');c.append(table(rows,[['Detection','title'],['Severity','severity'],['Created',r=>date(r.created)],['Evidence events',r=>r.event_count??JSON.parse(r.evidence).length]],{label:'Open case',fn:async r=>{await api('/api/cases',{alert_id:r.id});notice('Case created. Open Investigations to review.');}}));}
if(view==='cases'){
 c.append(table(await api('/api/cases'),[['Case','id'],['Title','title'],['Status','status'],['Created',r=>date(r.created)]],{label:'Investigate',fn:async r=>{
  const detail=await api('/api/case?id='+encodeURIComponent(r.id)),panel=el('article',undefined,'card');panel.append(el('h2',detail.case.title));const exportButton=el('button','Export evidence JSON');exportButton.onclick=()=>run(async()=>{const bundle=await api('/api/evidence/export',{case_id:r.id}),url=URL.createObjectURL(new Blob([JSON.stringify(bundle,null,2)],{type:'application/json'})),link=el('a');link.href=url;link.download='nova-case-'+r.id+'.json';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);notice('Evidence exported with a checksum. Use an operator signature for provenance.');});panel.append(exportButton);
  const status=el('select');status.setAttribute('aria-label','Case status');for(const value of ['open','investigating','resolved','closed']){const option=el('option',value);option.value=value;status.append(option);}status.value=detail.case.status;
  const note=el('textarea');note.placeholder='Add an investigation note';note.setAttribute('aria-label','Investigation note');note.maxLength=8192;note.rows=4;
  const save=el('button','Save case');save.onclick=()=>run(async()=>{await api('/api/cases/update',{id:r.id,status:status.value,...(note.value.trim()?{note:note.value.trim()}:{})});await load();notice('Case updated.');});
  panel.append(status,note,save,table(detail.notes,[['Time',n=>date(n.created)],['Analyst','actor'],['Note','note']]));c.append(panel);panel.scrollIntoView({behavior:'smooth'});
 }}));
}
if(view==='quarantine'){c.append(el('p','Activate the matching integration before replaying. Each event permits three replay attempts.'));c.append(table(await api('/api/quarantine'),[['Event','event_id'],['Reason','reason'],['Attempts','attempts']],{label:'Retry event',fn:async r=>{await api('/api/quarantine/replay',{event_id:r.event_id});notice('Replay queued. Refresh to check the result.');}}));}
if(view==='workflows'){
 c.append(el('p','Request a triage workflow for an alert. A different named administrator must approve it. Internal case actions are executed automatically after approval. Cancellation keeps any already-completed actions.'));
 const alerts=await api('/api/alerts'),select=el('select');select.setAttribute('aria-label','Alert for response workflow');for(const alert of alerts){const option=el('option',alert.title+' · '+alert.id.slice(0,12));option.value=alert.id;select.append(option);}const create=el('button','Request triage');create.disabled=!alerts.length;create.onclick=()=>run(async()=>{await api('/api/workflows',{request_key:crypto.randomUUID(),playbook:'triage-auth.v1',alert_id:select.value});await load();});c.append(select,create);
 const jobs=await api('/api/workflows');c.append(table(jobs,[['Workflow','id'],['State','state'],['Requested by','requester'],['Approved by','approver'],['Completed steps','step'],['Retry count','attempts']],{label:'Review',fn:async job=>{
  const panel=el('article',undefined,'card');panel.append(el('h2','Workflow review'),el('pre',JSON.stringify(JSON.parse(job.definition),null,2)),el('p','Requester: '+job.requester+' · Revision: '+job.revision));
  for(const action of ['approve','cancel','retry']){const b=el('button',action);b.onclick=()=>run(async()=>{await api('/api/workflows/transition',{id:job.id,revision:job.revision,action});await load();});panel.append(b);}c.append(panel);
 }}));
}
if(view==='external'){
 c.append(el('p','Request an action through an operator-configured connector. A different administrator must review and approve the exact parameters. Defender actions track provider completion. An uncertain submission requires provider review before requesting another action.'));
 const connectors=await api('/api/connectors'),alerts=await api('/api/alerts');
 if(!connectors.length)c.append(el('p','No external connectors are configured for this tenant.'));
 const connector=el('select'),alert=el('select'),parameters=el('textarea');connector.setAttribute('aria-label','Response connector');alert.setAttribute('aria-label','Related alert');parameters.setAttribute('aria-label','Connector parameters JSON');parameters.rows=5;parameters.value='{}';
 for(const item of connectors){const o=el('option',item.id);o.value=item.id;connector.append(o);}for(const item of alerts){const o=el('option',item.title+' · '+item.id.slice(0,8));o.value=item.id;alert.append(o);}
 const choose=()=>{const item=connectors.find(x=>x.id===connector.value);parameters.value=JSON.stringify(item?.kind==='defender'?{action:'isolate',machine_id:item.assets[0]}:{},null,2);};connector.onchange=choose;choose();
 const request=el('button','Request external action');request.disabled=!connectors.length||!alerts.length;request.onclick=()=>run(async()=>{await api('/api/external',{request_key:crypto.randomUUID(),connector:connector.value,alert_id:alert.value,parameters:JSON.parse(parameters.value)});await load();});c.append(connector,alert,parameters,request);
 const jobs=await api('/api/external');c.append(table(jobs,[['Connector','connector'],['State','state'],['Requester','requester'],['Approver','approver'],['Attempts','attempts'],['Error','last_error']],{label:'Review',fn:async job=>{const panel=el('article',undefined,'card');panel.append(el('h2','Review external action'),el('p','Connector: '+job.connector+' · Requester: '+job.requester),el('pre',JSON.stringify(JSON.parse(job.payload),null,2)));if(job.vendor_receipt)panel.append(el('h3','Provider receipt'),el('pre',JSON.stringify(JSON.parse(job.vendor_receipt),null,2)));if(job.state==='uncertain'){const operation=el('input');operation.placeholder='Verified Defender operation UUID';operation.setAttribute('aria-label','Defender operation UUID');const reconcile=el('button','Verify and reconcile');reconcile.onclick=()=>run(async()=>{await api('/api/external/transition',{id:job.id,revision:job.revision,action:'reconcile',operation_id:operation.value});await load();});panel.append(operation,reconcile);}if(job.state==='awaiting_approval'){for(const action of ['approve','cancel']){const b=el('button',action);b.onclick=()=>run(async()=>{await api('/api/external/transition',{id:job.id,revision:job.revision,action});await load();});panel.append(b);}}c.append(panel);}}));
}
if(view==='audit'){const verify=el('button','Verify linked audit history'),result=el('pre');verify.onclick=()=>run(async()=>{result.textContent=JSON.stringify(await api('/api/audit/checkpoint'),null,2);});c.append(el('p','Retain checkpoints outside this system to detect later history truncation. Pre-upgrade records are reported as unlinked.'),verify,result);c.append(table(await api('/api/audit'),[['Time',r=>date(r.created)],['Actor','actor'],['Action','action'],['Detail','detail']]));}}
$('#login-form').onsubmit=e=>{e.preventDefault();run(async()=>{token=$('#token').value.trim();await api('/api/health');$('#token').value='';$('#login').hidden=true;$('#workspace').hidden=false;await load();});};
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>run(async()=>{view=b.dataset.view;await load();}));
$('#refresh').onclick=()=>run(load);
$('#sample').onclick=()=>run(async()=>{const b=$('#sample');b.disabled=true;try{await api('/api/integrations/activate',{package:'auth-json'});const now=new Date().toISOString(),batch=crypto.randomUUID();await api('/api/events',{source:'sample-collector',integration:'auth-json',events:Array.from({length:5},(_,i)=>({id:batch+'-'+i,data:{timestamp:now,user:'demo-'+batch.slice(0,8),src_ip:'192.0.2.42',status:'failure',message:'Synthetic authentication failure — demonstration only'}}))});notice('Five synthetic events accepted. Refresh shortly to see the detection.');}finally{b.disabled=false;}});

$('#logout').onclick=()=>{token='';$('#token').value='';$('#content').replaceChildren();$('#workspace').hidden=true;$('#login').hidden=false;notice('Disconnected.');};
